### ISSUE TITLE
Ubuntu 24.04 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-android#25]
- Ensure CI uses the latest ubuntu
- Ensure dockerfile is updated to use ubuntu 24.04
- Ensure any documentation/references are updated

See https://github.com/overhangio/tutor/issues/1113 for context

**Comment by Abdul-Muqadim-Arbisoft** [comment]
The Jupyter plugin is functioning well, and the Ubuntu update has been successfully completed. Testing will proceed once the changes for Ubuntu 24.04 are merged upstream.
