### ISSUE TITLE
The android Docker image does not build on arm64

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-android#7]
Build fails with the following error:

    #25 [linux/arm64 11/11] RUN ./gradlew tasks
    #25 45.75 "Install Android SDK Platform 28 (revision: 6)" ready.
    #25 45.75 Installing Android SDK Platform 28 in /app/android-sdk/platforms/android-28
    #25 45.75 "Install Android SDK Platform 28 (revision: 6)" complete.
    #25 45.75 "Install Android SDK Platform 28 (revision: 6)" finished.
    #25 45.85 
    #25 45.85 FAILURE: Build failed with an exception.
    #25 45.85 
    #25 45.85 * What went wrong:
    #25 45.85 A problem occurred configuring project ':OpenEdXMobile'.
    #25 45.85 > Failed to install the following SDK components:
    #25 45.85       build-tools;28.0.3 Android SDK Build-Tools 28.0.3
    #25 45.85   Install the missing components using the SDK manager in Android Studio.

**Comment by ziafazal** [comment]
@muhammadali286 Is this issue still valid after your fixes of tutor-android plugin for Quince upgrade?

**Comment by muhammadali286** [comment]
The issue has been resolved after upgrading Ubuntu image, It was not related to arm64.

**Comment by regisb** [comment]
Awesome! Can you please remove the `IMAGES_BUILD_PLATFORM` key from the Gitlab CI file to build the image on arm64?

**Comment by muhammadali286** [comment]
@regisb please have a look [here](https://github.com/overhangio/tutor-android/pull/18)

**Comment by regisb** [comment]
Closed by #18
