### ISSUE TITLE
More info for README

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor-android#8]
Hi,
I wanted to share my feedback regarding the plugin. I must say, the plugin is awesome and has been working great for me. However, I faced an issue where the courses were not visible in the Discover section of the app. Later, I found out that setting "Mobile Course available" to true in the advanced settings of each course resolved the issue. Do you think it will be helpful to add this information to the documentation for future users?

**Comment by regisb** [comment]
Yes, most definitely.
